/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import BancoDeDados.DatabaseUtilit;
import BancoDeDados.SecretariaDAO;
import Modelo.Secretaria;
import Util.Utilitarios;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Lidia
 */
public class FrmSecretaria extends javax.swing.JFrame{
    int codSecretaria;
    Utilitarios util;
    FrmVisualizarSecretaria visualizaSecretaria;
    String operacao;
    /**
     * Creates new form FrmSecretaria
     */
    public FrmSecretaria(FrmVisualizarSecretaria form) {
        initComponents();
        util = new Utilitarios();
        this.visualizaSecretaria = form;
        this.setLocationRelativeTo(null);  //centralizar a tela
    }
    
    public void controlaBotoes(){
        if("salvar".equals(operacao))
        {
            util.limparCampos(pnlSecretaria);
            btnAlterar.setEnabled(false);
            btnSalvar.setEnabled(true);            
        } else if("alterar".equals(operacao))  {
            btnAlterar.setEnabled(true);
            btnSalvar.setEnabled(false);
        }
    }
    
    public void setCodigoSecretariaAlteracao(int codigo)
    {
        this.codSecretaria = codigo;
    }
    
    public void setTxtCpf(String cpf)
    {
        txtCpfSecretaria.setText(cpf);
    }
    
    public void setTxtRg(String rg)
    {
        txtRgSecretaria.setText(rg);
    }
    
    public void setTxtNome(String nome)
    {
        txtNomeSecretaria.setText(nome);
    }
    
    public void setTxtTelefone(String telefone)
    {
        txtTelefone.setText(telefone);
    }
    
    public void setTxtGenero(String genero)
    {
        if(genero.equals("F"))
         {
             cbxFeminino.setSelected(true);
         }
         else if(genero.equals("M"))
         {
             cbxMasculino.setSelected(true);
         }
    }
    
    public void setTxtCep(String cep)
    {
        txtCep.setText(cep);
    }
    
    public void setTxtNumCasa(String num)
    {
        txtNroCasa.setText(num);
    }
    
    public void setTxtCargo(String cargo)
    {
        //para preencher o cbbCargo de acordo com o escolhido
        int i = 0;
        int achou = 0; //nao achou
        while(achou != 1) //se achar pare
        {
            cbbCargo.setSelectedIndex(i); //seleciona o do index ipara verificar se é
            if (cbbCargo.getSelectedItem().toString().equals(cargo)) //caso o valor texto dele seja igual do cargo
            {
                cbbCargo.setSelectedIndex(i); //seleciona no form o item
                achou = 1; //achou recebe 1 para sair do while
            }
            i++; //vira 0
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSecretaria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeSecretaria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxFeminino = new javax.swing.JCheckBox();
        cbxMasculino = new javax.swing.JCheckBox();
        txtNroCasa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbbCargo = new javax.swing.JComboBox();
        txtRgSecretaria = new javax.swing.JFormattedTextField();
        txtCpfSecretaria = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        btnAlterar = new javax.swing.JButton();

        setTitle("Cadastro De Funcionário da Secretaria");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlSecretaria.setBorder(javax.swing.BorderFactory.createTitledBorder("Secretaria"));

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("RG:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Gênero:");

        cbxFeminino.setText("Feminino");
        cbxFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFemininoActionPerformed(evt);
            }
        });

        cbxMasculino.setText("Masculino");
        cbxMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMasculinoActionPerformed(evt);
            }
        });

        txtNroCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroCasaKeyTyped(evt);
            }
        });

        jLabel7.setText("Nº");

        jLabel6.setText("Cep:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel8.setText("Cargo:");

        cbbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secretário", "RH", "Administrador", "Estagiário", "Gerente" }));
        cbbCargo.setToolTipText("");

        try {
            txtRgSecretaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgSecretariaActionPerformed(evt);
            }
        });
        txtRgSecretaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRgSecretariaKeyTyped(evt);
            }
        });

        try {
            txtCpfSecretaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfSecretaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfSecretariaKeyTyped(evt);
            }
        });

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCepKeyTyped(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyTyped(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSecretariaLayout = new javax.swing.GroupLayout(pnlSecretaria);
        pnlSecretaria.setLayout(pnlSecretariaLayout);
        pnlSecretariaLayout.setHorizontalGroup(
            pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSecretariaLayout.createSequentialGroup()
                        .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCpfSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRgSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlSecretariaLayout.createSequentialGroup()
                        .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone))
                            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbxFeminino)
                        .addGap(18, 18, 18)
                        .addComponent(cbxMasculino)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSecretariaLayout.createSequentialGroup()
                        .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(btnAlterar)
                                .addGap(45, 45, 45)))
                        .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(40, 40, 40)
                                .addComponent(btnLimpar)
                                .addGap(40, 40, 40)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGap(45, 45, 45))
        );
        pnlSecretariaLayout.setVerticalGroup(
            pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtCpfSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRgSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbxFeminino)
                    .addComponent(cbxMasculino)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtNroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(btnSair)
                    .addComponent(btnAlterar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSecretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Util.Utilitarios util = new Utilitarios();
        util.fecharJanela(this);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        util.limparCampos(pnlSecretaria);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNroCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroCasaKeyTyped
        util.apenasNumeros(evt);
    }//GEN-LAST:event_txtNroCasaKeyTyped

    private void txtRgSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgSecretariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgSecretariaActionPerformed

    private void cbxFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFemininoActionPerformed
        //Se feminino selecionado, masculino não selecionado (desmarcado)
        cbxMasculino.setSelected(false);
    }//GEN-LAST:event_cbxFemininoActionPerformed

    private void cbxMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMasculinoActionPerformed
        //Se masculino selecionado, feminino nao selecionado (desmarcado)
        cbxFeminino.setSelected(false);
    }//GEN-LAST:event_cbxMasculinoActionPerformed

    private void txtCpfSecretariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfSecretariaKeyTyped
        util.apenasNumeros(evt);
    }//GEN-LAST:event_txtCpfSecretariaKeyTyped

    private void txtRgSecretariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRgSecretariaKeyTyped
        util.apenasNumeros(evt);
    }//GEN-LAST:event_txtRgSecretariaKeyTyped

    private void txtTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyTyped
        util.apenasNumeros(evt);
    }//GEN-LAST:event_txtTelefoneKeyTyped

    private void txtCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyTyped
        util.apenasNumeros(evt);
    }//GEN-LAST:event_txtCepKeyTyped

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNomeSecretaria.getText();
        String cpf = txtCpfSecretaria.getText();
        String rg = txtRgSecretaria.getText();
        String telefone = txtTelefone.getText();
        String genero = "";
            if(cbxFeminino.isSelected())
                genero = "F";
            if(cbxMasculino.isSelected())   
                genero = "M";
        String cep = txtCep.getText();
        String nroCasa = txtNroCasa.getText();
        String cargo = cbbCargo.getSelectedItem().toString();
        
        if("".equals(nome) || "".equals(cpf) || "".equals(rg) || "".equals(telefone) || "".equals(genero) || 
           "".equals(cep) || "".equals(nroCasa) || "".equals(cargo))
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
        else {
            Secretaria s = new Secretaria(cpf, rg, nome, telefone, genero, cep, nroCasa, cargo);
            DatabaseUtilit.Conectar();
            SecretariaDAO sDAO = new SecretariaDAO();
            sDAO.insereSecretaria(s);
            visualizaSecretaria.refresh();
            JOptionPane.showMessageDialog(null, "Salvo com sucesso");
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String nome = txtNomeSecretaria.getText();
        String cpf = txtCpfSecretaria.getText();
        String rg = txtRgSecretaria.getText();
        String telefone = txtTelefone.getText();
        String genero = "";
            if(cbxFeminino.isSelected())
                genero = "F";
            if(cbxMasculino.isSelected())   
                genero = "M";
        String cep = txtCep.getText();
        String nroCasa = txtNroCasa.getText();
        String cargo = cbbCargo.getSelectedItem().toString();
        
        if("".equals(nome) || "".equals(cpf) || "".equals(rg) || "".equals(telefone) || "".equals(genero) || 
           "".equals(cep) || "".equals(nroCasa) || "".equals(cargo))
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
        else {            
            Secretaria s = new Secretaria(codSecretaria, cpf, rg, nome, telefone, genero, cep, nroCasa, cargo);
            DatabaseUtilit.Conectar();
            SecretariaDAO sDAO = new SecretariaDAO();
            sDAO.updateSecretaria(s);
            visualizaSecretaria.refresh();
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        controlaBotoes(); // contra os botoes de alterar e salvar
    }//GEN-LAST:event_formComponentShown
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FrmSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbbCargo;
    private javax.swing.JCheckBox cbxFeminino;
    private javax.swing.JCheckBox cbxMasculino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnlSecretaria;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JFormattedTextField txtCpfSecretaria;
    private javax.swing.JTextField txtNomeSecretaria;
    private javax.swing.JTextField txtNroCasa;
    private javax.swing.JFormattedTextField txtRgSecretaria;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
