/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.MassagistaModelo;
import Util.Utilitarios;

/**
 *
 * @author Pessoal
 */
public class FrmVisualizarMassagista extends javax.swing.JFrame {
    private MassagistaModelo model;
    /**
     * Creates new form FrmVisualizarMassagista
     */
    
    public FrmVisualizarMassagista() {
        initComponents();
        this.setLocationRelativeTo(null);  //centralizar a tela
        configuraTabelaModelo();
        configuraTabelaColunas();
    }

    public void configuraTabelaModelo()
    {
        model = new MassagistaModelo();
        model.fillingRows();
        jtMassagista.setModel(model);
    }
    
     public void configuraTabelaModelo(String like) //polimorfismo
    {
        model = new MassagistaModelo();
        model.fillingRows(like);
        jtMassagista.setModel(model);
    }
     
     public void configuraTabelaModelo(int like) //polimorfismo
    {
        model = new MassagistaModelo();
        model.fillingRows(like);
        jtMassagista.setModel(model);
    }
     
    public void configuraTabelaColunas()
    {
        jtMassagista.getColumnModel().getColumn(0).setPreferredWidth(52);
        jtMassagista.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtMassagista.getColumnModel().getColumn(2).setPreferredWidth(160);
        jtMassagista.getColumnModel().getColumn(3).setPreferredWidth(120);   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisualizarCliente = new javax.swing.JPanel();
        cbbBuscarPor = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMassagista = new javax.swing.JTable();
        btnCadastro = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        brnAlterar = new javax.swing.JButton();
        btnVerTodos3 = new javax.swing.JButton();

        pnlVisualizarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualizar Funcionário de Atendimento"));

        cbbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "código", "nome" }));
        cbbBuscarPor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBuscarPorItemStateChanged(evt);
            }
        });

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jtMassagista);

        btnCadastro.setText("Cadastrar Funcionário");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        brnAlterar.setText("Alterar");
        brnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnAlterarActionPerformed(evt);
            }
        });

        btnVerTodos3.setText("Ver todos");
        btnVerTodos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodos3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVisualizarClienteLayout = new javax.swing.GroupLayout(pnlVisualizarCliente);
        pnlVisualizarCliente.setLayout(pnlVisualizarClienteLayout);
        pnlVisualizarClienteLayout.setHorizontalGroup(
            pnlVisualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVisualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVisualizarClienteLayout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cbbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerTodos3))
                    .addGroup(pnlVisualizarClienteLayout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addGap(80, 80, 80)
                        .addComponent(btnExcluir)
                        .addGap(110, 110, 110)
                        .addComponent(brnAlterar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlVisualizarClienteLayout.setVerticalGroup(
            pnlVisualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVisualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnVerTodos3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlVisualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisualizarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir)
                        .addComponent(brnAlterar))
                    .addComponent(btnCadastro))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVisualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVisualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(cbbBuscarPor.getSelectedItem().toString()=="código") { //Faz a busca por código
            configuraTabelaModelo(Integer.parseInt(txtPesquisa.getText() ) );
        }
        
        if(cbbBuscarPor.getSelectedItem().toString()=="nome") { //Faz a Busca por nome
            String nomeComAspas = "\'"+"%"+ txtPesquisa.getText()+"%"+"\'"; //concatena o nome com '% para busca com like
            configuraTabelaModelo(nomeComAspas); // '%exemplo%'
        }
        configuraTabelaColunas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        FrmMassagista objMa = new FrmMassagista();
        objMa.setVisible(true);

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void brnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnAlterarActionPerformed

    private void txtPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyTyped
        if(cbbBuscarPor.getSelectedItem().toString()=="código"){
            Util.Utilitarios util = new Utilitarios();
            util.apenasNumeros(evt);
        }
    }//GEN-LAST:event_txtPesquisaKeyTyped

    private void cbbBuscarPorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBuscarPorItemStateChanged
        if(cbbBuscarPor.getSelectedItem().toString()=="código"){
            txtPesquisa.setText("");
        }
        if(cbbBuscarPor.getSelectedItem().toString()=="nome"){
            txtPesquisa.setText("");
        }
    }//GEN-LAST:event_cbbBuscarPorItemStateChanged

    private void btnVerTodos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodos3ActionPerformed
        configuraTabelaModelo();
        configuraTabelaColunas();
        txtPesquisa.setText("");
    }//GEN-LAST:event_btnVerTodos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarMassagista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarMassagista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarMassagista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarMassagista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualizarMassagista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JButton btnVerTodos1;
    private javax.swing.JButton btnVerTodos2;
    private javax.swing.JButton btnVerTodos3;
    private javax.swing.JComboBox cbbBuscarPor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMassagista;
    private javax.swing.JPanel pnlVisualizarCliente;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
